### PR TITLE
Use stable Jabba script (and cache)

### PR DESCRIPTION
**Pull request by ignasi35**
References #55 (?)

Inspired by https://github.com/lagom/lagom/blob/master/.travis.yml

### CODE REVIEW

**Review by raboof — APPROVED** [review]
OK :)

We're using a lot of variations of this snippet - that's not necessarily a problem (no need to update the world when we come up with / try out an improvement in one place), but it'd be nice if we had a central place to keep track of what the 'current best practice' (tm) is :D

**Comment by raboof** [comment]
Fails though:

> $ jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version
> adopt@~1.adopt@1.8-0.0-0 is not a valid version

**Comment by ignasi35** [comment]
> We're using a lot of variations of this snippet - that's not necessarily a problem (no need to update the world when we come up with / try out an improvement in one place), but it'd be nice if we had a central place to keep track of what the 'current best practice' (tm) is :D

Completely agree, I think it's time we settled and started adopting https://github.com/scala/scala-dev/blob/scala-dev/travis/default.yml as a parent template and forget about the problem

**Comment by ignasi35** [comment]
raised https://github.com/akka/akka-meta/issues/141

**Pull request merged**
