### PR TITLE
chore: More fixes for next release

### PR DESCRIPTION
**Pull request by johanandren**
Missed two more things, now tested locally with the current milestones.

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Hmmm, maven template still contains akka-http2-support, I need to test locally for maven and gradle as well I guess

**Comment by johanandren** [comment]
The gradle build we have only supports Scala 2.12 so we either have to drop gradle from the quickstart or update it to something that works.

**Comment by johanandren** [comment]
Also, mail task in this CI didn't work

**Comment by patriknw** [comment]
don't know if it's the same, but this is what I did in Akka https://github.com/akka/akka/pull/32195

**Pull request merged**
